# Generated by Django 5.0.6 on 2024-06-25 18:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b31464f1-d242-4818-a5ef-7f1eb9beb3e9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b31464f1-d242-4818-a5ef-7f1eb9beb3e9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b31464f1-d242-4818-a5ef-7f1eb9beb3e9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b31464f1-d242-4818-a5ef-7f1eb9beb3e9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
